### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by nsheff**
- [x] changelog
- [x] version
- [x] pass R CMD check
- [x] pass biocCheck
- [x] rebuild full-power vignette (which is pre-built)

### CODE REVIEW

**Comment by nsheff** [comment]
vignettes are still failing, now with a duplicate chunk error in the intro vignette:

```
--- re-building ‘intro.Rmd’ using rmarkdown
Error: processing vignette 'intro.Rmd' failed with diagnostics:
Duplicate chunk label 'specificity-plot-multi', which has been used for the chunk:
op2 = calcOpenSignal(queryList, cellMatrix)
plotOpenSignal(op2)
Error: tangling vignette 'intro.Rmd' failed with diagnostics:
Duplicate chunk label 'specificity-plot-multi', which has been used for the chunk:
op2 = calcOpenSignal(queryList, cellMatrix)
plotOpenSignal(op2)
--- failed re-building ‘intro.Rmd’
```

**Comment by kkupkova** [comment]
> vignettes are still failing, now with a duplicate chunk error in the intro vignette:
> 
> ```
> --- re-building ‘intro.Rmd’ using rmarkdown
> Error: processing vignette 'intro.Rmd' failed with diagnostics:
> Duplicate chunk label 'specificity-plot-multi', which has been used for the chunk:
> op2 = calcOpenSignal(queryList, cellMatrix)
> plotOpenSignal(op2)
> Error: tangling vignette 'intro.Rmd' failed with diagnostics:
> Duplicate chunk label 'specificity-plot-multi', which has been used for the chunk:
> op2 = calcOpenSignal(queryList, cellMatrix)
> plotOpenSignal(op2)
> --- failed re-building ‘intro.Rmd’
> ```

I think that you just didn't have the latest version, I fixed the duplicity yesterday, and I don't have problem building intro.Rmd. But I am getting following error: 
```
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Scale for 'x' is already present. Adding another scale for 'x', which will
E> replace the existing scale.
E> Calculating overlaps...
E> Calculating overlaps...
E> --- finished re-building ‘intro.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘full-power.Rmd’
E> 
E> Error: Vignette re-bu
Type .Last.error.trace to see where the error occured
> .Last.error.trace

 Stack trace:

Error: 'col_ed' is not an exported object from 'namespace:cli'
```
@jpsmith5 do you know, where that might be coming from?

**Comment by kkupkova** [comment]
> > vignettes are still failing, now with a duplicate chunk error in the intro vignette:
> > ```
> > --- re-building ‘intro.Rmd’ using rmarkdown
> > Error: processing vignette 'intro.Rmd' failed with diagnostics:
> > Duplicate chunk label 'specificity-plot-multi', which has been used for the chunk:
> > op2 = calcOpenSignal(queryList, cellMatrix)
> > plotOpenSignal(op2)
> > Error: tangling vignette 'intro.Rmd' failed with diagnostics:
> > Duplicate chunk label 'specificity-plot-multi', which has been used for the chunk:
> > op2 = calcOpenSignal(queryList, cellMatrix)
> > plotOpenSignal(op2)
> > --- failed re-building ‘intro.Rmd’
> > ```
> 
> I think that you just didn't have the latest version, I fixed the duplicity yesterday, and I don't have problem building intro.Rmd. But I am getting following error:
> 
> ```
> Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
>   System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
> E> Scale for 'x' is already present. Adding another scale for 'x', which will
> E> replace the existing scale.
> E> Calculating overlaps...
> E> Calculating overlaps...
> E> --- finished re-building ‘intro.Rmd’
> E> 
> E> SUMMARY: processing the following file failed:
> E>   ‘full-power.Rmd’
> E> 
> E> Error: Vignette re-bu
> Type .Last.error.trace to see where the error occured
> > .Last.error.trace
> 
>  Stack trace:
> 
> Error: 'col_ed' is not an exported object from 'namespace:cli'
> ```
> 
> @jpsmith5 do you know, where that might be coming from?

My bad about intro, that was solved on dev. I will fix that.

**Comment by kkupkova** [comment]
I am also getting following when I run `devtools::run_examples`:

```
> ### Name: getChromSizesFromFasta
> ### Title: Get gene models from a remote or local FASTA file
> ### Aliases: getChromSizesFromFasta
> 
> ### ** Examples
> 
> CElegansUrl = "http://ftp.ensembl.org/pub/release-103/fasta/caenorhabditis_elegans/dna/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz"

> CElegansChromSizes = getChromSizesFromFasta(CElegansUrl, getwd())
File will be saved in: /Users/lilcrusher/code/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz
trying URL 'http://ftp.ensembl.org/pub/release-103/fasta/caenorhabditis_elegans/dna/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz'
downloaded 28.9 MB

Error in readDNAStringSet(fastaPath) : 
  could not find function "readDNAStringSet"
```

**Pull request merged**
