### PR TITLE
add unit test; Fix #70  

### LINKED ISSUE #70: extremely verbose function output
As shown in [this log](https://github.com/databio/GenomicDistributions/files/4499924/bedstat_log.txt), one of the functions in this package produces tens of thousands of warnings

It is _probably_ a result of the line below, but need to double check.

https://github.com/databio/GenomicDistributions/blob/757b74e1ff61abbbe175e02545b806ca2de715e1/R/content-plots.R#L75

### PR DESCRIPTION
**Pull request by joseverdezoto**
- added another unit test
- fixed extremely verbose output in `plotGCcontent` function
- small changes in GC content and open chromatin plots aesthetics

### CODE REVIEW

**Comment by stolarczyk** [comment]
can we make the x axis descriptions font smaller? It's overlapping in the plot below and hard to read


ews1_open_chromatin

**Comment by stolarczyk** [comment]
Oh, I think I used the released version of this package. Don't know if you worked on this here @joseverdezoto, maybe it's fixed

**Comment by joseverdezoto** [comment]
@stolarczyk  Yeah, I fixed that on my branch. I simply made the x axis descriptions font smaller. Could you test it from my branch?

**Comment by stolarczyk** [comment]
yes, I did and it looks much better. thx

**Comment by stolarczyk** [comment]
All the plots that are produced by bedstat look good, apart from this one:

ews1_widths_histogram

the descriptions over the bins can be made smaller, so they are visible

**Comment by nsheff** [comment]
maybe rotate them 90 degrees

**Comment by stolarczyk** [comment]
ews1_widths_histogram

**Comment by nsheff** [comment]
you need the position to change though so it's on top of rather than left of the point of interest. see how the left bar has disappeared? it's off the canvas.

**Comment by joseverdezoto** [comment]
I see. I think I'll just try to decrease the font size.

**Comment by joseverdezoto** [comment]
What about this?
[qthist_newfont.pdf](https://github.com/databio/GenomicDistributions/files/4560796/qthist_newfont.pdf)

**Comment by nsheff** [comment]
yes. but just make sure it still looks good when there's a lot less data.

**Comment by joseverdezoto** [comment]
In case you're wondering how it looks with less data.
[qthist_lessdata.pdf](https://github.com/databio/GenomicDistributions/files/4560867/qthist_lessdata.pdf)

**Pull request merged**
